import Image from 'next/image';
const steps=[['01','Discover','Understand the business, users, problems, processes and goals before writing a line of code.'],['02','Define','Scope the system — architecture, roadmap, metrics and what success actually looks like.'],['03','Design','Product and brand design that turns strategy into an experience people want to use.'],['04','Build','Senior engineers ship in weekly cycles. You see working progress, not decks.'],['05','Launch','Deploy, measure, harden. Real users, real data, real feedback from day one.'],['06','Grow','Double down on what works — acquisition, conversion, retention and automation.']];
const work=[
['TRADEGHAR','REAL ESTATE / AI / WORKFLOW AUTOMATION','7 AI-classified property categories','/projects/tradeghar-platform.png','/case-studies/tradeghar-real-estate-automation.pdf'],
['SAROX TECHNOLOGY','ELECTRICAL TESTING / DESKTOP APPLICATION','55% projected faster report completion','/projects/sarox-testing-dashboard.png','/case-studies/sarox-electrical-testing-automation.pdf'],
['SR FINCORP','FINANCIAL SERVICES / WEB / DIGITAL ENABLEMENT','+180% organic traffic in 90 days','/projects/sr-fincorp-digital-platform.jpg','https://ampliga.com/case-study-sr-fincorp/'],
['HNM REALTORS','REAL ESTATE / META CAMPAIGNS / LEAD GENERATION','1.28M campaign impressions','/projects/hnm-meta-campaign.jpg','https://ampliga.com/hnm-meta-campaign/'],
['PURELY SAATVIK','WELLNESS / BRAND / SHOPIFY COMMERCE','Global commerce with CRM automation','/projects/purely-saatvik-commerce.jpg','https://ampliga.com/purely-saatvik/']
];
const technologies=['React','Next.js','Vue','Node.js','TypeScript','Python','FastAPI','PostgreSQL','MongoDB','AWS','Docker','OpenAI','Claude','Gemini','Shopify'];
export default function OriginalHome(){return <><div className="project-cursor" aria-hidden="true">VIEW</div><header className="site-header"><a href="#top" className="wordmark logo-link" aria-label="Ampliga home"><Image src="/ampliga-logo.png" alt="Ampliga" width={58} height={42} priority/></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#technology">Insights</a></nav><a className="pill fixed-contact" href="#contact">Contact <span>↗</span></a><button className="hamb" aria-label="Open navigation"><i/><i/><i/></button></header><main id="top">
<section className="hero-ref" aria-label="Introduction"><div className="eyebrow"><b/>Independent Digital Studio</div><h1>We build digital<br/>systems that move<br/>businesses <em>forward.</em></h1><div className="hero-actions"><p>Technology, AI automation and growth systems<br className="desktop"/> for ambitious businesses.</p><div><a className="pill" href="#contact">Start a Project <span>↗</span></a><a href="#work">Explore Our Work ↓</a></div></div><div className="hero-meta"><span>Strategy&nbsp; / &nbsp;Design&nbsp; / &nbsp;Development&nbsp; / &nbsp;AI&nbsp; / &nbsp;Automation&nbsp; / &nbsp;Growth</span><span>EST. 2017</span></div><div className="hero-image"><Image src="/reference/dashboard-main.avif" alt="Product interface from an Ampliga-built intelligence platform" fill priority sizes="100vw"/></div></section>
<section className="what section-pad"><div className="eyebrow">WHAT WE DO — 01</div><div className="two-col"><h2>Build.<br/>Automate.<br/><em>Grow.</em></h2><p>We combine strategy, engineering, AI and growth to create digital systems built around real business outcomes — not deliverables that gather dust after launch day.</p></div></section>
<section className="selected section-pad" id="work"><div className="eyebrow">SELECTED WORK — 05</div><h2>Work that moves<br/>the business forward.</h2><article className="lead-case"><div className="lead-image"><Image src="/projects/tradeghar-platform.png" alt="Tradeghar AI real estate search platform" fill sizes="92vw"/></div><div className="case-copy"><div className="case-count"><span>01 / 05</span><span>8 WEEKS</span></div><h3>Tradeghar AI<br/>Real Estate Platform</h3><div className="tags"><span>AI / LLM</span><span>WORKFLOW AUTOMATION</span><span>WEB DEVELOPMENT</span></div><p>Turning unstructured WhatsApp property conversations into classified, deduplicated listings, intelligent matches and a centralized sales workflow.</p><strong>7 categories · 8 towns · processing in seconds</strong><a href="/case-studies/tradeghar-real-estate-automation.pdf" target="_blank" rel="noreferrer">View Case Study ↗</a></div></article></section>
<section className="disciplines-ref section-pad"><h2>Three disciplines.<br/>One growth system.</h2>{[['01','BUILD','Websites, products and software — engineered around your customers and operations.'],['02','AUTOMATE','AI agents and intelligent workflows that quietly remove repetitive work.'],['03','GROW','Acquisition, conversion and retention systems tied directly to revenue.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><b>↗</b></article>)}</section>
<section className="think"><div className="eyebrow">HOW WE THINK — 03</div><h2>Technology shouldn&apos;t just look <em>impressive.</em></h2><h2>It should make the business work <em>better.</em></h2><p>We connect strategy, engineering, automation and growth instead of treating them as separate disciplines. The result is fewer disconnected tools and systems designed around actual business outcomes.</p></section>
<section className="wod section-pad"><div className="eyebrow">FEATURED — SAROX / DESKTOP APPLICATION · AUTOMATION</div><div className="wod-head"><h2>Electrical testing.<br/>Reports, <em>automated.</em></h2><div><p>One offline-first desktop application for instrument readings, diagnostic calculations, technical review and consistent PDF/Excel reporting.</p><a href="/case-studies/sarox-electrical-testing-automation.pdf" target="_blank" rel="noreferrer">View Case Study ↗</a></div></div><div className="devices sarox-device"><div className="device-main"><Image src="/projects/sarox-testing-dashboard.png" alt="Sarox electrical testing live plot and reporting dashboard" fill sizes="92vw"/></div></div><div className="results"><div><b>65%</b><span>Projected reduction in manual reporting</span></div><div><b>55%</b><span>Projected faster report completion</span></div><div><b>18–28h</b><span>Projected monthly time saved</span></div></div></section>
<section className="process-ref"><div className="process-pin"><div className="eyebrow">HOW WE WORK — 05</div><div className="process-head"><h2>Senior thinking. Small teams. <em>Fast execution.</em></h2><p>Multidisciplinary teams work directly on each engagement — product thinking, engineering and growth, without layers of agency bureaucracy.</p></div><div className="steps">{steps.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><b>———→</b></article>)}</div></div></section>
<section className="business"><div className="eyebrow">THE BUSINESS DIFFERENCE</div><h2><span>We don&apos;t just deliver projects.</span><span>We solve business problems.</span></h2><div className="claims"><p>A website without traffic doesn&apos;t grow.</p><p>Marketing without conversion wastes money.</p><p>Automation without strategy creates complexity.</p><p>Technology without business context becomes expensive software.</p></div><h3>That&apos;s why we build the <em>system</em>—not just the individual pieces.</h3></section>
<section className="technology section-pad" id="technology"><div><h2>Built with the right tools.<br/><span>Not the trendy ones.</span></h2><p>Technology is selected around the problem — never the other way around.</p></div><div className="tech-marquee"><div className="tech-marquee-track">{[0,1].map(copy=><div className="tech-marquee-group" aria-hidden={copy===1} key={copy}>{technologies.map(tool=><span key={tool}>{tool}<i>•</i></span>)}</div>)}</div></div></section>
<section className="more-work section-pad"><div className="more-head"><h2>Selected work.</h2><span>REAL CLIENT SYSTEMS</span></div><div className="work-grid">{work.map(w=><article key={w[0]}><div className="work-image"><Image src={w[3]} alt={`${w[0]} — project visual`} fill sizes="(max-width: 767px) 100vw, 55vw"/></div><h3>{w[0]}</h3><p>{w[1]}</p><strong>{w[2]}</strong><a href={w[4]} target="_blank" rel="noreferrer">View Project ↗</a></article>)}</div></section>
<section className="about-ref section-pad" id="about"><div className="about-image"><Image src="/reference/team.avif" alt="Ampliga senior team working in the studio" fill sizes="92vw"/></div><div className="eyebrow">THE STUDIO</div><div className="about-copy"><h2>Strategy. Technology. Growth. <em>One team.</em></h2><div><p>We&apos;re a multidisciplinary team helping ambitious companies turn ideas, processes and growth challenges into digital systems that actually work. You work directly with the people building your product.</p><div className="about-stats"><span><b>14</b>Senior specialists</span><span><b>60+</b>Systems shipped</span><span><b>9 yrs</b>Building & growing</span></div><a href="#contact">Meet the team ↗</a></div></div></section>
<section className="contact-ref" id="contact"><div className="eyebrow"><b/>START A CONVERSATION</div><h2>Have something<br/><em>ambitious</em> in mind?</h2><a href="mailto:hello@ampliga.com">Let&apos;s build it. <span>↗</span></a><p>Prefer email? <a href="mailto:hello@ampliga.com">hello@ampliga.com</a></p></section></main>
<footer className="footer-ref"><div><a href="#top" className="wordmark logo-link footer-logo" aria-label="Ampliga home"><Image src="/ampliga-footer-wordmark.png" alt="Ampliga" width={2172} height={724}/></a><p>We build, automate and grow digital businesses. Independent studio, senior team, working worldwide from Gurugram.</p></div><nav><b>Studio</b><a href="#work">Work</a><a href="#about">About</a><a href="#technology">Insights</a><a href="#contact">Contact</a></nav><nav><b>Connect</b><a href="#">LinkedIn ↗</a><a href="#">Instagram ↗</a><a href="mailto:hello@ampliga.com">hello@ampliga.com</a></nav><div className="footer-bottom"><span>© Ampliga 2026</span><span>Gurugram, IN — working worldwide</span><span><a href="/privacy">Privacy</a>　 <a href="/terms">Terms</a></span></div></footer></>}
